name: CI

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install linter
        run: pip install ruff
      - name: Lint
        run: ruff check .

  build-windows:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      - name: Build (one-folder)
        run: pyinstaller --noconfirm --windowed --name "SVN Auto Commit Today" src/svn_today_commit.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: svn-auto-commit-today-win
          path: dist/**
